apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - workloads.yaml
configMapGenerator:
  - name: xiaoan-config
    literals:
      - STUDIO_ENV=prod
      - APP_ENV=production
      - APP_BASE_PATH=/xiaoan-platform/
      - API_ADDR=:8080
      - STREAM_ADDR=:8081
      - STORAGE_DRIVER=localfs
      - STORAGE_LOCAL_ROOT=/app/data/storage
  - name: xiaoan-nginx
    files:
      - default.conf=nginx.conf
