package adminrbac

const (
	PermissionEnterpriseOverviewRead   = "enterprise.overview.read"
	PermissionResourceAgentRead        = "resource.agent.read"
	PermissionResourceAgentManage      = "resource.agent.manage"
	PermissionResourceAppRead          = "resource.app.read"
	PermissionResourceAppManage        = "resource.app.manage"
	PermissionResourceGovernanceRead   = "resource.governance.read"
	PermissionResourceGovernanceManage = "resource.governance.manage"
	PermissionResourceAccessBypass     = "resource.access.bypass"
	PermissionAccessPolicyRead         = "access.policy.read"
	PermissionAccessPolicyManage       = "access.policy.manage"
	PermissionAccessGroupRead          = "access.group.read"
	PermissionAccessGroupManage        = "access.group.manage"
	PermissionAccessDiagnosisRead      = "access.diagnosis.read"
	PermissionDirectoryRead            = "directory.read"
	PermissionDirectorySyncRead        = "directory.sync.read"
	PermissionDirectorySyncManage      = "directory.sync.manage"
	PermissionAdminUserRead            = "admin.user.read"
	PermissionAdminUserManage          = "admin.user.manage"
	PermissionAdminRoleRead            = "admin.role.read"
	PermissionAdminRoleManage          = "admin.role.manage"
	PermissionProviderRead             = "provider.read"
	PermissionProviderManage           = "provider.manage"
	PermissionProviderTest             = "provider.test"
	PermissionRuntimeRead              = "runtime.read"
	PermissionRuntimeManage            = "runtime.manage"
	PermissionRunMonitorRead           = "run.monitor.read"
	PermissionRunManage                = "run.manage"
	PermissionAuditRead                = "audit.read"
	PermissionAuditExport              = "audit.export"
	PermissionSettingsRead             = "settings.read"
	PermissionSettingsManage           = "settings.manage"
)
