apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eboat-ai-ns
resources:
  - ../../base
  - ingress.yaml
images:
  - name: xiaoan-backend
    newName: harbor.hengan.com:8086/eboat2/xiaoan-backend
    newTag: REPLACE_RELEASE
  - name: xiaoan-web
    newName: harbor.hengan.com:8086/eboat2/xiaoan-web
    newTag: REPLACE_RELEASE
